djangoapp/apps/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

djangoapp/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
]

djangoapp/apps/home/models.py
from django.db import models

# Create your models here.

djangoapp/apps/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def home(request):

    return render(
        request,
        'home/acesso.html'
        )

djangoapp/apps/home/templates/home/acesso.html
{% extends 'base/base.html' %}

{% block body_base %}
<div class="container-fluid">
    <div class="row">
        <p>
            Digite um texto aqui

        </p>
    </div>

</div>

{% endblock body_base %}

djangoapp/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>PROJETO DJANGO START</title>

        <link rel="shortcut icon" type="image/ico" href="{% static 'media/base/imagens/favicon.ico' %}" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body class="bg-primary text-white">
        <header>
            {% include 'base/navbar.html' %}
        </header>

        <div class="container-fluid bg-white text-black">
            <div class="row justify-content-md-center">
                <div class="col">

                </div>
                <div class="col-md-auto text-center  py-5">
                    <main>
                        {% block body_base %}
                        {% endblock body_base %}
                    </main>
                </div>
                <div class="col">
                </div>

            </div>
        </div>
        {% include 'base/footer.html' %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    </body>
</html>

djangoapp/templates/base/footer.html
<footer class="bg-primary py-4 mt-5">

    <div class="container-fluid text-white d-flex justify-content-center align-items-end">
        <div class="row justify-content-center">
            <div class="col-5 col-lg-5 text-left">
                <h5 class="text-uppercase fw-bold text-info">
                    Sobre
                </h5>
                <p>
                   PROJETO DJANGO SOBRE
                </p>
            </div>

            <div class="col-5 col-lg-5">
                <h5 class="text-uppercase fw-bold text-info">
                    Outras
                </h5>
                <p>
                    PROJETO DJANGO2
                </p>
            </div>
        </div>
    </div>
</footer>

djangoapp/templates/base/formulario_base.html
{% extends 'base/base.html' %}

{% block body_base %}
<div class="container-fluid">
    <div class="row">
        <form method="post" action="{% url caminho_url %}">
            {% csrf_token %}
            <div>
                <div>
                    <strong>{{ titulo_formulario }}</strong>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                {% for field in form %}
                    <div class="form-group">
                        <div class="row py-3">
                            {% if field.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ field.label_tag }}
                                    {{ field.errors }}
                                    {{ field}}
                                </div>
                            {% else %}
                                {{ field.label_tag }}
                                {{ field }}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                
            </div>
            <br><br>
            <button type="submit" class="btn btn-success col-12 mt-3">{{ nome_button }}</button>
    
        </form>
    </div>

</div>

{% endblock body_base %}

djangoapp/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid col-sm-6 col-md-8">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'media/base/imagens/django.png' %}" alt="LOGO AQUI"  height="40"></a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        PROJETO DJANGO 3
                    </a>
                    <ul class="dropdown-menu">
                        <li><p class="dropdown-item">NOME COLAPSE</p></li>
                        <li><a class="dropdown-item px-5" href="#">ITEM 1</a></li> 
                        <li><a class="dropdown-item px-5" href="#">ITEM 2</a></li> 
                    </ul>
                </li>
            </ul>


        <div class="dropdown col-md-4">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Olá {{ user.first_name }} {{ user.last_name }}
                    </a>

                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}"> Admin</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}"> Sair</a></li>
                    </ul>
                    
                </li>
            </ul>
        </div>
    </div>
</nav>